/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package utils;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class Encryption {

    public Encryption() {
    }

    
    public String getMd5(String input) {
        try {
            // Phương thức tĩnh getInstance được gọi với thuật toán băm MD5 
            String salt = "ajoigfsm59;.13rd+!afda"; // Định nghĩa một salt để tăng cường bảo mật
            input = input + salt; // Thêm salt vào đầu vào
            MessageDigest md = MessageDigest.getInstance("MD5"); // Tạo đối tượng MessageDigest với thuật toán MD5

            // Phương thức digest() được gọi để tính toán giá trị băm của đầu vào 
            // digest() trả về mảng byte 
            byte[] messageDigest = md.digest(input.getBytes()); // Băm đầu vào đã được bổ sung salt

            // Chuyển đổi mảng byte thành biểu diễn số signum 
            BigInteger no = new BigInteger(1, messageDigest);

            // Chuyển đổi giá trị băm thành giá trị hex 
            String hashtext = no.toString(16); // Chuyển đổi số thành chuỗi hệ thập lục phân
            while (hashtext.length() < 32) { // Đảm bảo độ dài chuỗi băm là 32 ký tự
                hashtext = "0" + hashtext; // Thêm 0 vào đầu chuỗi nếu cần
            }
            return hashtext; // Trả về chuỗi băm MD5
        } // Để chỉ định thuật toán băm sai 
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e); // Ném ra ngoại lệ nếu thuật toán không tồn tại
        }
    }

    public static void main(String[] args) {
        Encryption e = new Encryption();
        System.out.print("Input password: ");
        Scanner kb = new Scanner(System.in);
        String pass = kb.nextLine();
        System.out.println("Your Password generated by MD5 is: " + e.getMd5(pass));
        kb.close();
    }
}
